specUri: github.com/lovethedrake/drakespec
specVersion: v0.6.0

snippets:

  baseGoContainer: &baseGoContainer
    name: go
    image: brigadecore/go-tools:v0.1.0
    sourceMountPath: /devdrake
    workingDirectory: /devdrake
    tty: true
    resources:
      cpu:
        maxMillicores: 2000
      memory:
        maxMegabytes: 2048

  baseDemoContainer: &baseDemoContainer
    name: demo
    image: debian:stretch

jobs:

################################################################################
# Demo jobs                                                                    #
################################################################################

  foo:
    primaryContainer:
      <<: *baseDemoContainer
      command: ["echo"]
      args: ["foo"]

  bar:
    primaryContainer:
      <<: *baseDemoContainer
      command: ["echo"]
      args: ["bar"]

  fail:
    primaryContainer:
      <<: *baseDemoContainer
      command: ["false"]

  # This job demonstrates two containers networked together.
  # This doesn't work in Brigade / k8s yet because job / pod completion is based
  # on ALL containers having exited and the redis sidecar never will. There's
  # a KEP open to fix this.
  redis:
    sidecarContainers:
    - name: redis
      image: redis:latest
    primaryContainer:
      name: redis-cli
      image: redis:latest
      sourceMountPath: /demo
      workingDirectory: /demo
      command: ["scripts/demo/redis.sh"]

################################################################################
# Utility jobs                                                                 #
################################################################################

  vendor:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "run", "mage.go", "vendor"]
    sourceMountMode: RW

################################################################################
# Test jobs                                                                    #
################################################################################

  verify-vendored-code:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "run", "mage.go", "verifyVendor"]
    sourceMountMode: COPY

  test-unit:
    primaryContainer:
      <<: *baseGoContainer
      command: ["go", "run", "mage.go", "test"]
      sharedStorageMountPath: /shared
    sourceMountMode: COPY

  upload-coverage-report:
    primaryContainer:
      <<: *baseGoContainer
      command: ["bash", "-c"]
      args: ["bash <(curl -s https://codecov.io/bash) -f /shared/coverage.txt"]
      sharedStorageMountPath: /shared

  lint:
    primaryContainer:
      <<: *baseGoContainer
      command: ["golangci-lint", "run"]
      args:
      - ./cmd/...
      - ./pkg/...

################################################################################
# Build / publish jobs                                                         #
################################################################################

  build-linux-amd64:
    primaryContainer:
      <<: *baseGoContainer
      environment:
        CGO_ENABLED: "0"
      command: ["scripts/build.sh"]
      args: ["linux", "amd64"]
      sharedStorageMountPath: /shared

  build-darwin-amd64:
    primaryContainer:
      <<: *baseGoContainer
      environment:
        CGO_ENABLED: "0"
      command: ["scripts/build.sh"]
      args: ["darwin", "amd64"]
      sharedStorageMountPath: /shared

  build-windows-amd64:
    primaryContainer:
      <<: *baseGoContainer
      environment:
        CGO_ENABLED: "0"
      command: ["scripts/build.sh"]
      args: ["windows", "amd64"]
      sharedStorageMountPath: /shared

  publish-binaries:
    primaryContainer:
      <<: *baseGoContainer
      command: ["scripts/publish.sh"]
      sharedStorageMountPath: /shared

################################################################################
# Pipelines                                                                    #
################################################################################

pipelines:

################################################################################
# Demo pipelines                                                               #
################################################################################

  foobar:
    jobs:
    - name: foo
    - name: bar
      dependencies:
      - foo

################################################################################
# CI pipeline                                                                 #
################################################################################

  ci:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        pullRequest:
          targetBranches:
            only:
            - /.*/
        push:
          branches:
            only:
            - /.*/
    jobs:
    - name: lint
    - name: verify-vendored-code
    - name: test-unit
    - name: upload-coverage-report
      dependencies:
      - test-unit
    - name: build-linux-amd64
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
    - name: build-darwin-amd64
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit
    - name: build-windows-amd64
      dependencies:
      - lint
      - verify-vendored-code
      - test-unit

################################################################################
# Release pipeline                                                             #
################################################################################

  release:
    triggers:
    # This is a placeholder. No formal spec exists for this trigger yet.
    # Stay tuned.
    - specUri: github.com/lovethedrake/drakespec-github
      specVersion: v1.0.0
      config:
        push:
          tags:
            only:
            - /v[0-9]+(\.[0-9]+)*(\-.+)?/
    jobs:
    - name: build-linux-amd64
    - name: build-darwin-amd64
    - name: build-windows-amd64
    - name: publish-binaries
      dependencies:
      - build-linux-amd64
      - build-darwin-amd64
      - build-windows-amd64
